//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxMVCDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_TBL
    {
        public int Order_id { get; set; }
        public string Order_Descr { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Product_id { get; set; }
    
        public virtual Product_TBL Product_TBL { get; set; }
        public virtual TBL_Custo TBL_Custo { get; set; }
    }
}
