//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxMVCDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_TBL
    {
        public Product_TBL()
        {
            this.Order_TBL = new HashSet<Order_TBL>();
        }
    
        public int Product_id { get; set; }
        public string Product_name { get; set; }
        public string Product_category { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> QTE { get; set; }
    
        public virtual ICollection<Order_TBL> Order_TBL { get; set; }
    }
}
