//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxMVCDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Custo
    {
        public TBL_Custo()
        {
            this.Order_TBL = new HashSet<Order_TBL>();
        }
    
        public int Customer_ID { get; set; }
        public string customer_name { get; set; }
        public Nullable<int> customer_phone { get; set; }
        public string Customer_EMIL { get; set; }
    
        public virtual ICollection<Order_TBL> Order_TBL { get; set; }
    }
}
